title:              Young Sun Park's Blog
email:              ddspys@gmail.com
description:        Technical & Life Blog
author:             Young Sun Park
baseurl:            "/blog"
url:                "https://ddspys.github.io"

# Social Profiles
twitter_username:   
github_username:    ddspys
facebook_username:  
instagram_username:  coffeejoongdokja
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   # UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
